name: Deploy Vite Project to GitHub Pages

on:
  push:
    branches:
      - main # Asegúrate de que esta sea tu rama principal
  workflow_dispatch: # Permite ejecutar el flujo de trabajo manualmente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Puedes probar con '18' si '20' da problemas
          cache: 'npm'

      - name: Install project dependencies
        run: npm install

      - name: Build Vite project for production
        run: npm run build # Este comando es el que genera tu carpeta dist

      - name: Upload production build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # Esta es la carpeta que GitHub Pages debe servir

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
